# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Divekit Roadmap
email:
description: >- # this means to ignore newlines until "baseurl:"
  Anforderungssammlung für die Weiterentwicklung von Divekit
baseurl:  # the subpath of your site, e.g. /blog
url: "https://divekit.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
#theme: jekyll-theme-midnight
theme: minima
plugins:
  - jekyll-feed


collections:
  authors:
    output: true
  functionalRequirements:
    output: true
  goals:
    output: true
  interviews:
    output: true
  literatureReferences:
    output: true
  nonFunctionalRequirements:
    output: true
  personas:
    output: true
  reviews:
    output: true
  scenarios:
    output: true
  stakeholderRoles:
    output: true
  stakeholders:
    output: true
  surveys:
    output: true
  systemContextElements:
    output: true
  useCaseDiagrams:
    output: true
  useCases:
    output: true
  userStories:
    output: true
  workshops:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "functionalRequirements"
    values:
      layout: "functionalRequirement"
  - scope:
      path: ""
      type: "goals"
    values:
      layout: "goal"
  - scope:
      path: ""
      type: "interviews"
    values:
      layout: "interview"
  - scope:
      path: ""
      type: "literatureReferences"
    values:
      layout: "literatureReference"
  - scope:
      path: ""
      type: "personas"
    values:
      layout: "persona"
  - scope:
      path: ""
      type: "reviews"
    values:
      layout: "review"
  - scope:
      path: ""
      type: "scenarios"
    values:
      layout: "scenario"
  - scope:
      path: ""
      type: "stakeholderRoles"
    values:
      layout: "stakeholderRole"
  - scope:
      path: ""
      type: "stakeholders"
    values:
      layout: "stakeholder"
  - scope:
      path: ""
      type: "surveys"
    values:
      layout: "survey"
  - scope:
      path: ""
      type: "systemContextElements"
    values:
      layout: "systemContextElement"
  - scope:
      path: ""
      type: "useCaseDiagrams"
    values:
      layout: "useCaseDiagram"
  - scope:
      path: ""
      type: "useCases"
    values:
      layout: "useCase"
  - scope:
      path: ""
      type: "userStories"
    values:
      layout: "userStory"
  - scope:
      path: ""
      type: "workshops"
    values:
      layout: "workshop"
